# Generated by Django 5.2.7 on 2025-10-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quotes', '0002_tag_alter_quote_author_remove_quote_tags_quote_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born_date',
            field=models.CharField(),
        ),
    ]
